module.exports = {
	confirm_punish: require('./confirm_punish.js'),
	message_punish: require('./message_punish.js'),
	message_modlogs: require('./message_modlogs.js'),
	randomCharacters: require('./randomCharacters.js'),
	removeAcents: require('./removeAcents.js'),
	formatSizeUnits: require('./formatSizeUnits.js'),
	format_time: require('./format_time.js'),
	ObjRef: require('./objref/ObjRef.js'),
	highest_position: require('./highest_position.js'),
	timeString: require('./timeString.js'),
	validateUser: require('./validateUser.js'),
	chunk: require('./chunk.js'),
	replace_placeholders: require('./replace_placeholders.js'),
	calculate_levels: require('./calculate_levels.js'),
	checkSimilarityStrings: require('./checkSimilarityStrings.js'),
};